// <auto-generated />
using Amarinfinancial.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amarinfinancial.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Amarinfinancial.Models.Finance", b =>
                {
                    b.Property<int>("MembersID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("groups")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("transactions")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MembersID");

                    b.ToTable("Finances");
                });
#pragma warning restore 612, 618
        }
    }
}
